// <auto-generated />
using System;
using CovidApp.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CovidApp.Infra.Migrations
{
    [DbContext(typeof(CovidDbContext))]
    [Migration("20210203153302_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CovidApp.Core.Entities.CasoCovid", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Ativos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confirmados")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confirmados");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<int>("Mortes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mortes");

                    b.Property<string>("Pais")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_pais");

                    b.Property<int>("Recuperados")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recuperados");

                    b.HasKey("Id");

                    b.ToTable("casos_covid");
                });
#pragma warning restore 612, 618
        }
    }
}
